refactor(bin/git-update): use Bash builtin echo
* Updated documentation
* Use Bash's builtin 'echo' instead of /usr/bin/echo

diff --git a/bin/git-update b/bin/git-update
--- a/bin/git-update
+++ b/bin/git-update
@@ -12,9 +12,26 @@
 #   Otherwise, the `git pull' tasks are performed within the current
 #   directory.
 #
+# INSTALLATION
+#   I recommend you use the following procedure to "install" this script:
+#       1) $ test -d ~/.local/bin/ || mkdir -p ~/.local/bin/
+#       2) $ ln -s ~/git/ece3220/bin/git-update ~/.local/bin/
+#       3) $ git config --global alias.update '!'"$HOME/.local/bin/git-update"
+#
+# NOTES
+#   Within the local Git repository, if the main or develop branch has
+#   unstaged changes, git-update will fail to update that branch.  You'll
+#   need to either commit or stash the branch's unstaged changes prior to
+#   invoking git-update.
+#
+# EXAMPLE
+#   $ git update ~/git/ece3220
+#   OR,
+#   $ cd ~/git/ece3220
+#   $ git update
+#
 set -eu
 
-declare -r ECHO=/usr/bin/echo
 declare -r GIT=/usr/bin/git
 
 #==========================================================================
@@ -27,11 +44,11 @@ function git_checkout_branch()
     local exit_value=0
 
     if "${GIT}" show-ref --quiet refs/heads/${branch_name}; then
-        "${ECHO}" "Updating branch '${branch_name}'"
+        echo "Updating branch '${branch_name}'"
         "$GIT" checkout "${branch_name}"
     else
-        >&2 "${ECHO}" ":: NOTICE :: This Git repository does not have a local branch named '${branch_name}'."
-        >&2 "${ECHO}" "Skipping branch '${branch_name}'."
+        >&2 echo ":: NOTICE :: This Git repository does not have a local branch named '${branch_name}'."
+        >&2 echo "Skipping branch '${branch_name}'."
         exit_value=1
     fi
     return $exit_value
@@ -64,12 +81,12 @@ if [[ $# -gt 0 ]]; then
         # program /usr/bin/cd. --end note]
         cd "$1"
     else
-        >&2 "${ECHO}" ":: ERROR ::  Directory '$1' does not exist."
+        >&2 echo ":: ERROR ::  Directory '$1' does not exist."
         exit 1
     fi
 fi
 
-"${ECHO}" -n "Updating folder: "
+echo -n "Updating folder: "
 pwd
 
 git_pull_branch "develop"
