build(Makefile): updated remove_folder()

diff --git a/make/Makefile b/make/Makefile
--- a/make/Makefile
+++ b/make/Makefile
@@ -33,6 +33,9 @@ CXX   := g++
 STRIP := strip
 
 
+MAKEFILE_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
+MAKEFILE_DIR := $(notdir $(patsubst %/,%,$(dir $(mkfile_path))))
+
 # [Optional]  To build this project with a toolchain other than the default
 # toolchain that Make uses, create within the current working directory a
 # makefile named `toolchain.mk' and within it define (at a minimum) the
@@ -708,15 +711,15 @@ _basic_clean::
 # Delete all build products *except* the program file.
 .PHONY: mostly-clean
 mostly-clean:: _basic_clean
-	$(call remove_folder,$(DEPDIR))
-	$(call remove_folder,$(BUILDDIR))
+	@$(call remove_folder,$(DEPDIR))
+	@$(call remove_folder,$(BUILDDIR))
 
 # Delete the documentation folders 'html' and 'latex' (e.g., documentation
 # generated by doxygen).
 .PHONY: doc-clean
 doc-clean:
-	$(call remove_folder,html)
-	$(call remove_folder,latex)
+	@$(call remove_folder,html)
+	@$(call remove_folder,latex)
 
 # Delete all build products that are files (do not delete directories).
 .PHONY: clean
@@ -815,18 +818,31 @@ endif
 
 
 # Removes a folder only if it resides within the current working directory.
+# @param[in] folder The folder to be deleted.
+# @param[in] verbose (optional) Pass the value 'verbose' for verbose output.
 # [Note 1. If a path string contains one or more backslash characters '\',
 # each backslash is converted into an underscore. (And don't forget! 
 # Ubuntu and Raspberry Pi OS use dash, not sh or bash, to execute shell
 # commands.) --end note]
 define remove_folder
-	@if [ -n "$(1)" -a -d "$(1)" ]; then \
+	if [ -z "$(1)" ] || [ "$(1)" == '.' ]; then \
+		if [ "$(2)" == "verbose" ]; then \
+			>&2 echo ":: REMOVE_FOLDER :: Invalid folder name '$(1)'."; \
+		fi; \
+	elif ! [ -d "$(1)" ]; then \
+		if [ "$(2)" == "verbose" ]; then \
+			>&2 echo ":: REMOVE_FOLDER :: Folder '$(1)' does not exist."; \
+		fi; \
+	else \
 		realpath_one="$$(/usr/bin/realpath "$(1)")"; \
 		realpath_one="$$(echo "$${realpath_one}" | /usr/bin/tr '\\' '_')"; \
 		realpath_pwd="$$(/usr/bin/realpath .)"; \
 		realpath_pwd="$$(echo "$${realpath_pwd}" | /usr/bin/tr '\\' '_')"; \
-		if echo "$${realpath_one}" | /usr/bin/grep -q "$${realpath_pwd}"; then \
-			rm -fr "$(1)"; \
+		if check="$$(expr "$${realpath_one}" : "\($${realpath_pwd}\)")"; then \
+			echo "rm -fr "$(1)""; \
+			/usr/bin/rm -fr "$(1)"; \
+		else \
+			>&2 echo ":: REMOVE_FOLDER :: Folder '$(1)' does not reside in the current working directory. Ignoring..."; \
 		fi; \
 	fi
 endef
